### ISSUE TITLE
Feature Checklist

### ISSUE THREAD

**Issue by rhengles** [arijs/ariframework#1]
- [x] Parse templates
- [x] Mechanism to observe and be notified of property changes
- [x] Render one component
- [x] Interpolate variables in text content
- [x] Render sub components inside a component
- [x] Allow components to be replaced after render
- [x] Mechanism to load a component dynamically
- [x] "if" directive
- [ ] "for" directive
- [ ] Bind attributes
- [ ] Bind events
- [ ] Implement slots
- [ ] Write tests
- [ ] Write documentation
- [ ] Write router
- [ ] Write server side rendering
